// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADRxCvJPwdVLUOK7H7tgS1KMijB9cr1wM',
    appId: '1:949242046245:web:3fd7b0c89905f6ddd09ccc',
    messagingSenderId: '949242046245',
    projectId: 'strantum-1d12c',
    authDomain: 'strantum-1d12c.firebaseapp.com',
    storageBucket: 'strantum-1d12c.appspot.com',
    measurementId: 'G-B7WWRRS769',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvH28ASZV9vxtRTBWC9LIB0gmv_2RP8dw',
    appId: '1:949242046245:android:a060367a5295e002d09ccc',
    messagingSenderId: '949242046245',
    projectId: 'strantum-1d12c',
    storageBucket: 'strantum-1d12c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiQcE1sD_jlpxoQJtxrSDucKgLNav6EfY',
    appId: '1:949242046245:ios:6c7524d592272550d09ccc',
    messagingSenderId: '949242046245',
    projectId: 'strantum-1d12c',
    storageBucket: 'strantum-1d12c.appspot.com',
    iosBundleId: 'com.example.strantum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiQcE1sD_jlpxoQJtxrSDucKgLNav6EfY',
    appId: '1:949242046245:ios:6c7524d592272550d09ccc',
    messagingSenderId: '949242046245',
    projectId: 'strantum-1d12c',
    storageBucket: 'strantum-1d12c.appspot.com',
    iosBundleId: 'com.example.strantum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADRxCvJPwdVLUOK7H7tgS1KMijB9cr1wM',
    appId: '1:949242046245:web:0fb7bcba28aa8ba7d09ccc',
    messagingSenderId: '949242046245',
    projectId: 'strantum-1d12c',
    authDomain: 'strantum-1d12c.firebaseapp.com',
    storageBucket: 'strantum-1d12c.appspot.com',
    measurementId: 'G-5WN56FXGXS',
  );
}
